### ISSUE TITLE
Use normal randoms for generating random directions in samplers

### ISSUE THREAD

**Issue by exaexa** [LCSB-BioCore/COBREXA.jl#178]
`rand() * objective` generates diagonal-biased directions. Using `randn()` prevents this behavior.

(Also, consider using `StableRNGs`.)

**Comment by stelmo** [comment]
Is this still an issue @exaexa ?

**Comment by exaexa** [comment]
No, we don't really _generate_ any directions at all now. So closing, thanks for ping. :]
