### ISSUE TITLE
implement CI from forks

### ISSUE THREAD

**Issue by laurentheirendt** [LCSB-BioCore/COBREXA.jl#262]
issue is that the CI cannot be triggered from a fork: https://gitlab.com/gitlab-org/gitlab/-/issues/218712

**Comment by laurentheirendt** [comment]
some references:

https://github.com/brndnmtthws/labhub
https://gitlab.com/gitlab-org/gitlab/-/issues/5667

We might need to set up labhub

**Comment by laurentheirendt** [comment]
#279 is related

**Comment by exaexa** [comment]
@laurentheirendt how urgent is this? Now it's for v2.0 but I guess the whole thing will be much more involved, possibly not even an issue directly here but at the place where we put the labhub.

**Comment by exaexa** [comment]
Possible alternative solution for now: is it possible to make a github workflow that runs the test ONLY if it detects that it's running in another repository than this?

**Comment by laurentheirendt** [comment]
this is not really urgent 😄 

yes, that could work

**Comment by exaexa** [comment]
Just to close this issue -- what if we supply a small github action with "just test" that gets triggered only if the repo is _not_ this central one?

**Comment by laurentheirendt** [comment]
not sure that is possible

**Comment by exaexa** [comment]
solved differently (we use github matrix in C2)
