### ISSUE TITLE
Homogenize add/remove functions and add in place versions

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#281]
Currently `CoreModel` has `remove_reactions`, `add_reactions` etc. and `StandardModel` has `add!`, and `rm!`. Convert the `StandardModel` functions into their `CoreModel` counterparts to keep the names of the functions the same. 

Also, add in place versions of these functions where possible.

**Comment by htpusa** [comment]
There is also the `verify_consistency` functionality in `CoreModel` which is currently unfinished. The goal was to check, when adding a reaction, if the reaction is already in the model, and if so, if the definitions agree.

Personally I'd like to have this, mainly for checking if two reactions with the same id are truly the same. However, it needs to be decided what the desired behaviour would be (eg, different id, same stoichiometry, what do).

**Comment by stelmo** [comment]
From discussion with @exaexa:

make these functions generic e.g.
```julia
remove_metabolites(mets) -> (model::CoreModel) -> remove_metabolites(model, mets)
remove_metabolites(mets) -> (model::StandardModel) -> remove_metabolites(model, mets)
 ```
method ambiguity. Make generic instead and then specialize on model type.

**Comment by stelmo** [comment]
From #197: 
Currently removing reactions or metabolites breaks the model. Making removals work.
Be smart: rm_metabolites!(model,metabolites(model)[rowCount(stoichiometry(model) .!= 0).>0])

**Comment by stelmo** [comment]
> From #197:
> Currently removing reactions or metabolites breaks the model. Making removals work.
> Be smart: rm_metabolites!(model,metabolites(model)[rowCount(stoichiometry(model) .!= 0).>0])

actually, an informative error function in `stoichiometry` is supplied - this should alert the user. probably not required to fix now.
