### ISSUE TITLE
solver precompilation in tests blocks unnecessarily

### ISSUE THREAD

**Issue by exaexa** [LCSB-BioCore/COBREXA.jl#287]
JuMP+Tulip JIT takes quite a bit of time (~50 secs here). In the tests, the main worker JITs this in `test/base/solver.jl`, the other workers start in FVA tests. That wastest 50 seconds because the JIT doesn't run in parallel althought it could.

*Proposed solution*

kick the solver tests off with something parallel, so that the precompilation is also parallel.

*Outcome*

hopefully -60s test time, much less skewed test timing.

**Comment by laurentheirendt** [comment]
maybe we can add Tulip to the base image?

**Comment by exaexa** [comment]
not sure if that helps, I've got tulip installed and precompiled and using it first time in jump in a "fresh" julia process takes ~60s nevertheless

**Comment by laurentheirendt** [comment]
sure, but in the Docker image, we could freeze the state after `using Tulip`

**Comment by exaexa** [comment]
wait, you can transplant a running julia to the testing env?

**Comment by laurentheirendt** [comment]
let's try ...
