### ISSUE TITLE
Improve coverage of src/base/utils/StandardModel.jl

### ISSUE THREAD

**Issue by exaexa** [LCSB-BioCore/COBREXA.jl#288]
https://codecov.io/gh/LCSB-BioCore/COBREXA.jl/src/master/src/base/utils/StandardModel.jl

The `verbose` branch in `exchange_reactions` is completely untested, I'd either :axe: it (if the user needs a more complete output, then the actual output should be more complete, not "printed side effects". If the verbose variant is to be kept, consider using the standard per-category "debug" logging functions.

**Comment by stelmo** [comment]
See PR #299
