### ISSUE TITLE
Feature to get atomic counts in reactions

### ISSUE THREAD

**Issue by VictorVeraFrazao** [LCSB-BioCore/COBREXA.jl#311]
For purposes of flux normalization over carbon-moles I would like to access the amount of carbons within the biomass reaction. Unfortunately there don't seem to be any function to directly access it.
I would suggest a function that takes the atomic count of each participant of the reaction and multiply it with the corresponding stoichiometric value, and add up the resulting numbers for each element. The output could be a dictionary with the elements for keys and the total count within the reaction for values. 
I would be grateful if you consider my suggestion to be included into your module.

**Comment by stelmo** [comment]
Hi Victor,

Thanks for using COBREXA! We have added the feature you requested, see #312. This feature should get merged pretty quickly, hopefully before the next release. Let us know if you have any other questions/recommendations!
