### ISSUE TITLE
change the auto-formatting mechanism

### ISSUE THREAD

**Issue by laurentheirendt** [LCSB-BioCore/COBREXA.jl#322]
Instead of the current mechanism of auto-formatting, the idea is to:
- have @cylon-x comment on each new PR/state change whether there is code formatting required
- before the PR gets merged, a repo maintainer can trigger formatting by commenting: `@cylon-x format`
- the bot @cylon-x will the open a new PR against that branch from which it got triggered with a formatting commit

@exaexa I hope that is along those lines what we discussed.

This will also solve #315

**Comment by exaexa** [comment]
> @exaexa I hope that is along those lines what we discussed.

Yeah sounds perfect. Not sure how complicated it would be to have a "rolling overview comment" that summarizes the latest state of the formatting there, like codecov does with coverage, but it would be really cool.

**Comment by exaexa** [comment]
@laurentheirendt let's push this a bit. I have some autoformatting ready at https://github.com/exaexa/ci-format-test , also working at https://github.com/LCSB-BioCore/COBREXA.jl/pull/599 . That implements both the new "format by comment", and "format check" as we have now. Uses only github actions. Is there a way to port that to cylon? Or perhaps, don't we want to keep cylon lightweight and instead have this done by a simple github action? (I can publish this as github action at the action market.)

**Comment by laurentheirendt** [comment]
The action would be triggered automatically, right?

**Comment by exaexa** [comment]
Actually solved in #615
