### ISSUE TITLE
More running changes

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#358]
More small improvements, don't address these, I will when I am done adding to this list. However, feel free to comment on the changes, maybe I am wrong...

- [ ] `Reaction` has fields called `lb` and `ub`, change these to `lower_bound` and `upper_bound` to match the more verbose style we have adopted. ⚠️ this would be a breaking change
- [ ] make a `set_objective!` function
- [ ] `change_constraint` let it be possible to use kwargs to only change a specific bound
- [ ] `flux_summary` should not error when `nothing` is input, but rather display a message saying the solver didn't return a solution
- [ ] `metabolite_fluxes` why ignore zero flux metabolites? change the function to drop the dependence on `_constants.tolerance`
- [ ] change documentation for `change_objective` to reflect the fact that MOI is not necessarily imported e.g. `change_objective(...; sense=MOI.MIN_SENSE)` will error if `JuMP` is not imported, rather have the docstring read: `change_objective(...; sense=COBREXA.MOI.MIN_SENSE)`
- [ ] `flux_summary` should not error when there is no biomass or import or export reactions

**Comment by laurentheirendt** [comment]
`lb` and `ub` are so well established that I wouldn't change them ...

**Comment by exaexa** [comment]
I'm converting this to discussion (multi-issues like this are basically unclosable)
