### ISSUE TITLE
✨ Add in place versions of `remove_reaction` and `remove_metabolite` + plural variants for `CoreModel` and `StandardModel`

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#362]
These functions are nice to have

**Comment by exaexa** [comment]
Let's elaborate a bit-- I guess this change would be something similar to the `change_bounds` macro-generated stuff we did last time?

**Comment by stelmo** [comment]
Yep, exactly like that :)
