### ISSUE TITLE
Add latex completion hints for non-ascii characters in docs

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#382]
Look at the docstring of ⟶ and → in the docs, they look identical. This could be confusing, add the latex shortcuts to the docs to make the difference obvious, e.g. in this case `\rightarrow<tab> = →` and `\longrightarrow<tab> = ⟶`

**Comment by exaexa** [comment]
I still kinda think that we shold avoid having both → and →.

**Comment by stelmo** [comment]
ah okay, I am open to deleting one of them actually! Maybe the shorter one?

**Comment by exaexa** [comment]
keep →, delete the long variant (it would be weird to only have an adjectivized variant)

**Comment by stelmo** [comment]
but but but the long one looks prettier :)

**Comment by stelmo** [comment]
The more I read my own comments, the more I realize that I just love good looking code/docs

**Comment by exaexa** [comment]
I wish we could just write the nice interoperable `->` and have editors that display it the right way.

**Comment by stelmo** [comment]
So it turns out I already added the latex completion stuff to the docs! https://lcsb-biocore.github.io/COBREXA.jl/stable/notebooks/5_basic_stdmodel_construction/#Add-reactions-to-the-model

**Comment by stelmo** [comment]
hmm although these arrows kinda clash with ligatures... Like it is hard to distinguish -> from \longrightarrow
