### ISSUE TITLE
Banner doesn't display

### ISSUE THREAD

**Issue by laurentheirendt** [LCSB-BioCore/COBREXA.jl#390]
**Summary**

sometimes when doing using COBREXA, the banner doesn’t show

**Environment**

Linux CentOS, Julia 1.6.0

**Steps to reproduce**

    1. launch Julia
    2. type: `using COBREXA`

**Expected behavior**

the banner is displayed

**Actual behavior**

the banner is not displayed

**Comment by exaexa** [comment]
there would need to be a specific functionality to support this (I'll ask around). Current banner is printed out basically as a side effect of the package precompilation, which "runs" all the code to create the modules (e.g. expand macros).
