### ISSUE TITLE
`StandardModel` does not read in metabolite/reaction/gene names

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#392]
```julia
model = load_model(StandardModel, modelpath) # json formatted model
```

yields:
```julia
OrderedCollections.OrderedDict{String, Reaction} with 2712 entries:
"CYTDK2" => Reaction("CYTDK2", nothing, Dict("cmp_c"=>1.0, "gdp_c"=>1.0, "cytd_c"=>-1.0…  
"XPPT" => Reaction("XPPT", nothing, Dict("xan_c"=>-1.0, "prpp_c"=>-1.0, "ppi_c"...
```

And similarly for metabolites and genes, notice how the `name` field is `nothing`, which is not true... also, should this rather be `missing`?

**Comment by exaexa** [comment]
this is likely; last time I saw that SBML.jl actually doesn't export reaction names. Consistency would be welcome here for sure.
