### ISSUE TITLE
Simple export of results in JSON (orig: Should we have a function that exports fluxes in a dict for visualization in Escher?)

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#397]
I think [Escher](https://escher.github.io/) is used a lot for quickly visualizing a metabolic network (? is this true, in my experience yes, but who knows in general...). Should we export a convenience function that replaces this:
```julia
using JSON

open("fluxes.json", "w") do io
    JSON.print(op, sol)
end
```
with this:
```julia
write_fluxes(sol, "fluxes.json")
```
?

**Comment by exaexa** [comment]
What should the output look like? If it's complicated, the solution should be in a separate package, if not (looks like a oneliner) there's no point in wrapping it.

**Comment by stelmo** [comment]
the output is literally a dictionary that looks like this:
```
{"PACOAT":4.6450163980355336e-12,"Zn2tex":0.00017049999996743281,"GUI1":0.0,"DXYLK":-0.0,"FE3DCITtonex":2.3365114205877606e-11,"METSOXR1":1.4097176498459716e-12,"FACOAL180t2pp":2.6335029857180776e-11,"CBL1tonex":-0.0,...
```
This would literally just be a convenience thing, since I often write out those 3 lines of code :)

**Comment by exaexa** [comment]
This is better implemented in JSON package, they should have `printfile`. Can you add it there?

**Comment by exaexa** [comment]
This is gonna get fixed elsewhere, closing for now.
