### ISSUE TITLE
Use `Dictionary.jl` instead of `OrderedCollections.jl` in `StandardModel`

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#434]
It seems `Dictionary.jl` might be a better option, investigate + implement if so.

**Comment by exaexa** [comment]
:+1: 
Side observation: it could be sufficient to just reimplement&use the `index` thing from `Dictionary` which seems ultra-useful. Certainly would remove a lot of `indexin` business which inherently O(n²).

**Comment by exaexa** [comment]
actually a tiny wrapper function like `_findindex` or `_findinexes` that reports a _good_ error message on failure would perhaps be the best. :D

**Comment by stelmo** [comment]
Shelving this for now, not clear if performance improvement is worth the effort of a breaking change/dep change
