### ISSUE TITLE
Add genes and gene reaction rules to `CoreModel`

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#439]
The only really important feature missing from `CoreModel`s is genes and gene reaction rules. What is the most efficient way to add this information to the models and still have it be efficient?

**Comment by exaexa** [comment]
are there any MAT models around that contain the GRRs?

**Comment by stelmo** [comment]
Yep, all the mat models from the BiGG database, e.g. iML1515, iJR904, iAF1260, etc.

**Comment by exaexa** [comment]
Closing this (thanks @htpusa ) :tada:
