### ISSUE TITLE
Add MOMENT algorithm

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#446]
The moment algorithm is quite nice since it includes enzyme capacity constraints in a more mechanistically sound way than crowding. Add like crowding as a problem modification. Also, maybe do the same with thermoFBA - expose a modification function... It would be nice to be able to combine them. Will do when I get back - could be very cool.

**Comment by exaexa** [comment]
Already contained in #455, closing here
