### ISSUE TITLE
unique links to contributing guide

### ISSUE THREAD

**Issue by laurentheirendt** [LCSB-BioCore/COBREXA.jl#490]
Throughout the documentation, some of the links point to https://github.com/LCSB-BioCore/COBREXA.jl/blob/master/.github/CONTRIBUTING.md and some others to https://lcsb-biocore.github.io/COBREXA.jl/stable/howToContribute/.

I think they should only point to https://lcsb-biocore.github.io/COBREXA.jl/stable/howToContribute/

On that page as well, the emojis are not rendered properly 😃

**Comment by exaexa** [comment]
Test of unicode replacement
🎉  👍
