### ISSUE TITLE
link to `Edit on Github` does not work anymore

### ISSUE THREAD

**Issue by laurentheirendt** [LCSB-BioCore/COBREXA.jl#496]
![image](https://user-images.githubusercontent.com/20812112/140268321-89c4b0bc-e1f2-4454-adf1-c1b87d4c87f4.png)

in the new documentation, the link `Edit on Github` does not work anymore and points to github.com instead of the repo

**Comment by laurentheirendt** [comment]
This actually leads to other links not working anymore

![image](https://user-images.githubusercontent.com/20812112/140268625-d4ddfa56-ba80-4483-b4ed-be242e550f21.png)

**Comment by exaexa** [comment]
This got fixed by #500 but the docs still didn't deploy; waiting for #503

**Comment by exaexa** [comment]
The current deployed develop seems fixed properly, closing :]
