### ISSUE TITLE
Fix versioning dropdown in documentation

### ISSUE THREAD

**Issue by laurentheirendt** [LCSB-BioCore/COBREXA.jl#498]
Just opening this here not to forget

![image](https://user-images.githubusercontent.com/20812112/140268805-3c63a6e2-2e75-4aa8-a70f-c54962d9ed47.png)

**Comment by exaexa** [comment]
This should kinda fix itself when there are more versions (will add eventually); but needs to wait. PS I mistakenly marked this in a commit. :D

**Comment by laurentheirendt** [comment]
The previous versions should be generated manually - I propose to leave this issue open until actually fixed.

**Comment by exaexa** [comment]
why did I close this btw? (sorry, probably clicked "close with coment" by mistake)

**Comment by exaexa** [comment]
ah yeah the thing got merged to master but still no deploys
