### ISSUE TITLE
fluxVariabilityAnalysis doesn't check termination status

### ISSUE THREAD

**Issue by laurentheirendt** [LCSB-BioCore/COBREXA.jl#5]
original issue: https://git-r3lab.uni.lu/PerMedCoE/COBREXA.jl/-/issues/22

**Comment by exaexa** [comment]
This is actually solved now, see here (it returns `nothing` in case the optimization failed for whatever reason)
https://github.com/LCSB-BioCore/COBREXA.jl/blob/master/src/analysis/flux_variability_analysis.jl#L152
