### ISSUE TITLE
Are knockouts potentially confusing?

### ISSUE THREAD

**Issue by htpusa** [LCSB-BioCore/COBREXA.jl#520]
The way I see it, `knockout` right now is an in-place modification. However:

```
using COBREXA,Tulip
m=load_model("test/downloaded/e_coli_core.mat")
om=make_optimization_model(m,Tulip.Optimizer)
```

```
knockout("b3916")(m,om)
knockout("b1723")(m,om)

julia> COBREXA.normalized_rhs(om[:ubs][1])
1000.0
```

```
knockout(["b3916";"b1723"])(m,om)

julia> COBREXA.normalized_rhs(om[:ubs][1])
0.0
```

IMO, this is potentially unexpected.

**Comment by exaexa** [comment]
by "potentially confusing" you mean "the combinations might not work right" ? :]

**Comment by htpusa** [comment]
I mean from the naming, arguments and behaviour it's not clear what exactly the function does or should be expected to do.

**Comment by exaexa** [comment]
Anyway yeah this is expected -- the information about "having the gene knocked out" is not stored in the model, so the second call does not know that the first call already knocked out a gene that would be required to keep a reaction running if the second gene is missing.

We should write this in the docs explicitly. Thanks for pointing it out.

**Comment by stelmo** [comment]
Should we call them `gene_knockout` and make a function for `reaction_knockout`? I think `knockout` is too generic... A novice might put a reaction id in there and wonder why things break...

**Comment by stelmo** [comment]
Yes, I think adding that to the docs is important, especially if people are tempted to do something like:
```julia
flux_balance_analysis_dict(
  model,
  Tulip.Optimizer;
  modifications = [
    knockout("a"),
    knockout("b"),
  ]
)
```
and expect memory

**Comment by htpusa** [comment]
I'm even thinking, since `Gene` is an object, should we have expression states for genes? Could even be a positive real, with zero standing for inactive/absent? This could make integrating transcriptomics/proteomics very intuitive.

**Comment by stelmo** [comment]
Yeah, that would be a nice addition

**Comment by exaexa** [comment]
+1, folding the logic into data is right. Actually I was contemplating on something similar already with #510.

Technically we can do an "overlay" type that just adds the functionality to the inner type, just as CoreModelCoupled adds the coupling.

Random idea:

```julia
struct WithGeneActivation{M :> MetabolicModel}
  m::M
  modified_genes::Dict{String,Float64}
end
...
