### ISSUE TITLE
Change reaction constraints using un-mangled reaction id

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#633]
right now the change constraint modification uses `reactions(model)` to set bounds on variables. For more complicated models like `GeckoModel`s you can't use the natural (un-mangled) reaction ids to set the bounds on variables. We should fix it so that the users can do this without having to look-up the mangled ones (or changing the underlying model).

**Comment by exaexa** [comment]
this could basically multiply the constraint through the reaction_fluxes matrix and add it as is. Certainly doable, I'll have a look at it.

OTOH if possible one should preferably set the "base" reaction bounds on the original model before it gets through gecko construction.

**Comment by exaexa** [comment]
naming: `change_constraint` vs `change_flux_bound` ?

(future after rename: `change_variable_constraint` vs `change_reaction_constraint` ?)

**Comment by exaexa** [comment]
solved differently (no mangling in C2)
