### ISSUE TITLE
Full-text search for metabolite/reaction/gene IDs

### ISSUE THREAD

**Issue by exaexa** [LCSB-BioCore/COBREXA.jl#652]
## Target functionality

It is sometimes quite complicated to quickly find a ID (often numeric one) for a reaction in the model without looking at all possible reaction names and annotations.

There should be a search function, intended for interactive use only, that can quickly find the IDs. 

## Desired output

```
search_model(m, "glc")
```
says something like
```
Yeah your ID is either  M_glc__d_c or M_glc__d_e
```

**Comment by stelmo** [comment]
Maybe we should just search SBO terms instead... "Good" models should have SBO terms for all the reactions and metabolites... This will probably fail spectacularly for 80% of models because people just don't add this info into their models..

**Comment by stelmo** [comment]
See [here](https://www.ebi.ac.uk/ols/index) for more info

**Comment by exaexa** [comment]
moving to AFBCMs for future consideration
