### ISSUE TITLE
Add stoichiometry to gene reaction rules

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#655]
Currently a gene reaction rule is expressed like this: `G1 & G2 = [[G1, G2]]` however, genes typically have stoichiometry associated with them (see the enzyme constrained stuff). How about we make the grrs incorporate this stoichiometry like `[[1@G1, 2@G2]]` to denote a complex formed with one G1 and two G2s. This will make enzyme constrained models more robust and is step 1 on the route to ME models. We could have a default that if there is no explicit `@` then `1@` is assumed.

**Comment by stelmo** [comment]
So perhaps a better way to do it is to have grrs appear as tuples like so: `reaction.grr = [[(1, g1), (2, g2)], [(1, g3)]]`

**Comment by stelmo** [comment]
Closed with #689

**Comment by exaexa** [comment]
Solved in `next`
