### ISSUE TITLE
Sampling size parameters are not very intuitive

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#657]
Why does the sampling procedure generate as many samples as one inputs warmup points? Shouldn't it return as many samples as requested in `sample_iters`? See below for a MWE:
```julia
using COBREXA, Gurobi

model = load_model(StandardModel, joinpath("data", "models", "e_coli_core.json"))

warmup_points = warmup_from_variability(
    model, 
    Gurobi.Optimizer,
    10,
    modifications = [silence]
)

samples = affine_hit_and_run(
    model,
    warmup_points,
    sample_iters = 1:1:5
)
```
I expect 5 samples here, but I get 5 * 10 = 50. Is this expected behaviour?

**Comment by exaexa** [comment]
solved in cobrexa 2
