### ISSUE TITLE
Add support for ME models

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#664]
Currently COBREXA only supports M (metabolic) models. Increasingly people are building ME (metabolic and expression) models. These are much more complicated since they include ribosomes etc., and are no longer LPs, but are much more expressive and capture substantially more physiology than basic M models. We should make a model type that can handle them. Also, `StandardModel` should be extended to be able to cope with whatever extra info is required to build them (#655 is step 1 in this direction). See here for the only other attempt at this:

https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006302

**Comment by exaexa** [comment]
can we make a list of the stuff that this will break?

Currently I'm only aware about the extended GRRs (where you need stoichiometry for each gene building piece).

**Comment by stelmo** [comment]
Probably want to go with RBA models instead

**Comment by stelmo** [comment]
#717 is a start along with this process. However, full RBA might have to wait until later since I doubt it will be done within the next 2 months (the window for 2.0)

**Comment by exaexa** [comment]
Made trivial in cobrexa 2, closing
