### ISSUE TITLE
Drop OSQP and use Clarabel instead for QPs

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#666]
I have found [Clarabel](https://github.com/oxfordcontrol/Clarabel.jl) to give better/more consistent solutions than OSQP, let's switch. Only affects the tests.

**Comment by stelmo** [comment]
Need to wait on this until they fix https://github.com/oxfordcontrol/Clarabel.jl/issues/99

**Comment by exaexa** [comment]
actually we should benchmark this stuff a bit, I'll be benchmarking this for PMC eventually so we should eventually be able to make actual educated choice

**Comment by exaexa** [comment]
anyway the preliminary tests look VEEEEEEEERY good.
