### ISSUE TITLE
Collect package download information

### ISSUE THREAD

**Issue by stelmo** [LCSB-BioCore/COBREXA.jl#685]
We should collect download stats. This will be useful when requesting sustainability for the project and motivate its importance. Not sure how to remove CI from the stats, but maybe relative growth would be enough...

**Comment by stelmo** [comment]
from Genie's creator I think? I am also not sure :/ It will probably involve a higher level understanding of git infrastructure, hence me passing the ball :)

**Comment by exaexa** [comment]
apparently it's from here: https://discourse.julialang.org/t/announcing-package-download-stats/69073

**Comment by stelmo** [comment]
we should put the badge on the repo

**Comment by exaexa** [comment]
Turns out this is basically impossible to do reliably unless we host everything on our own infrastructure, at which point we still can't really collect much info because of gdpr issues. I'm closing this as impractical, feel free to reopen later if some concrete solution surfaces.
