### ISSUE TITLE
JUMP time limit

### ISSUE THREAD

**Issue by exaexa** [LCSB-BioCore/COBREXA.jl#807]
### Discussed in https://github.com/LCSB-BioCore/COBREXA.jl/discussions/806

Originally posted by @mihai-sysbio December 13, 2023:

> I've seen drastically different results from Tulip and GLPK. One likely cause is the default time limits they have. In the case of GLPK, I would like to increase it, so I was looking at [setting a time limit in JuMP](https://jump.dev/JuMP.jl/stable/manual/models/#Set-a-time-limit) or [directly in GLPK](https://github.com/jump-dev/GLPK.jl#use-with-jump), but I'm not sure if this is compatible with the COBREXA setup.

This should become something like

```julia
flux_balance_analysis(...; modifications=[set_time_limit(1235)])
```

...or so.

Thanks for the idea.

**Comment by stelmo** [comment]
Should be easy to do.

**Comment by exaexa** [comment]
Apparently there's even a solver-unspecific option for doing this with JuMP. I added an implementation of that into the `next` branch. Currently no plan to backport it to 1.x releases, but pls ping us if you'd use that, it's just an extra few minutes of commit juggling. :D

**Comment by mihai-sysbio** [comment]
Sounds good @exaexa I am happy with what I have and I am fully onboard with not back-porting this.

**Comment by exaexa** [comment]
OK I'll assume this as solved in 2.x and close, and add our favorite mark for code that didn't quite make it, so that we don't lose it for 1.x ... 

Thanks again for reporting!
