### ISSUE TITLE
Genes not parsed if they have an "@" symbol

### ISSUE THREAD

**Issue by HettieC** [LCSB-BioCore/COBREXA.jl#823]
Hello! 

If gene IDs have an "@" symbol, they do not parse correctly:

`_parse_grr_to_sbml("A@1")`
returns the error 
`ERROR: DomainError with A@1:
cannot parse GRR
Stacktrace:
 [1] _parse_grr_to_sbml(str::String)
   @ COBREXA ~/.julia/packages/COBREXA/IheBW/src/base/utils/gene_associations.jl:189
 [2] top-level scope
   @ ~/Documents/Projects/ECYeast/src/plotting/conservation_of_metabolism.jl:8
`

**Comment by exaexa** [comment]
Fixed in `develop` and in JSONFBC package. Will release eventually, please use the develop version for now if required.
