### ISSUE TITLE
We should eventually use StableRNGs for sampling and all other random number generation.

### ISSUE THREAD

**Issue by exaexa** [LCSB-BioCore/COBREXA.jl#84]
_Originally posted by @exaexa in https://github.com/LCSB-BioCore/COBREXA.jl/pull/78#discussion_r611621577_

Also see the related issue in GigaSOM:
https://github.com/LCSB-BioCore/GigaSOM.jl/pull/147

**Comment by stelmo** [comment]
@exaexa can I close this?

**Comment by exaexa** [comment]
nope, this is required for reproducibility.
